./similarity 工人 教师
./similarity 工人 科学家
./similarity 工人 农民
./similarity 工人 运动员
./similarity 教师 科学家
./similarity 教师 农民
./similarity 教师 运动员
./similarity 科学家 农民
./similarity 科学家 运动员
./similarity 农民 运动员
./similarity 中国 美国
./similarity 中国 联合国
./similarity 中国 安理会
./similarity 中国 欧洲
./similarity 粉红 红
./similarity 粉红 红色
./similarity 粉红 绿
./similarity 粉红 颜色
./similarity 绿 颜色
./similarity 十分 非常
./similarity 十分 特别
./similarity 思考 考虑
./similarity 思考 思想
./similarity 跑 跳
./similarity 跑 跳舞
./similarity 跑 运行